In [11]:
import numpy as np

A = np.array([[1,-4],[-4,1]])
B = np.array([[1,-8],[-8,2]])

# **Primera parte de los ejercicios**

In [12]:
A + B

array([[  2, -12],
       [-12,   3]])

In [17]:
A - 0.5 * B

array([[-1.,  6.],
       [ 9.,  1.]])

In [14]:
5*A

array([[  5, -20],
       [-20,   5]])

# **Segunda parte de los ejercicios**

In [15]:
A = np.array([[1,3],[5,7]])
B = np.array([[4,-6],[-8,12]])

In [6]:
np.absolute(np.linalg.det(A))

np.float64(7.999999999999998)

In [7]:
np.linalg.inv(A)

array([[-0.875,  0.375],
       [ 0.625, -0.125]])

In [8]:
if np.linalg.det(B) != 0:
    print(np.linalg.inv(B))
else:
    print("La matriz no tiene inversa, su determinante es 0")

La matriz no tiene inversa, su determinante es 0


In [9]:
np.dot(A, np.linalg.inv(A))

array([[1., 0.],
       [0., 1.]])

In [10]:
np.linalg.inv(np.linalg.inv(A))

array([[1., 3.],
       [5., 7.]])