In [ ]:
import numpy as np

## Ejercicio 1: Crear un arreglo

1. Crear un arreglo de números del 0 al 10 e imprime su tipo de datos y su dimensión.
2. Convierte el arreglo en un arreglo de tipo float y vuelve a imprimirlo.

In [ ]:
# Crear un arreglo de números del 0 al 10
array = np.arange(11)
print(f"El arrelo es: {array}\n")

print(f"El tipo de datos que almacena es: {array.dtype}\n")  # Impresión de tipos de dato
print(f"La dimesión del arreglo es: {array.ndim}\n") # Impresión de dimensión

array_float = array.astype(float) # Conversión del arreglo a flotante
print(f"El arreglo modificado es: {array_float}") # Impresión del arreglo convertido

El arrelo es: [ 0  1  2  3  4  5  6  7  8  9 10]

El tipo de datos que almacena es: int64

La dimesión del arreglo es: 1

El arreglo modificado es: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


---
## Ejercicio 2: Operaciones básicas

1. Genera dos arreglos aleatorios de 5 elementos cada uno.
2. Realiza las siguientes operaciones entre ambos arreglos a cada elemento:
  - Suma.
  - Resta.
  - Multiplicación.
  - División.
3. Calcula el promedio, la mediana y la desviación estándar de uno de los arreglos.

In [ ]:
import numpy as np

# Genera dos arreglos aleatorios entero de 5 elementos cada uno de (0 a 99)
arreglo1 = np.random.randint(0, 100, 5)
arreglo2 = np.random.randint(0, 100, 5)

print("Arreglo 1:", arreglo1)
print("Arreglo 2:", arreglo2)

# Realiza las operaciones elemento a elemento
suma = arreglo1 + arreglo2
resta = arreglo1 - arreglo2
multiplicacion = arreglo1 * arreglo2
division = arreglo1 / arreglo2

print("\nSuma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

# Calcula el promedio, la mediana y la desviación estándar de arreglo1
promedio = np.mean(arreglo1)
mediana = np.median(arreglo1)
desviacion_estandar = np.std(arreglo1)

# Mensajes de salida
print("\nPromedio de arreglo1:", promedio)
print("Mediana de arreglo1:", mediana)
print("Desviación estándar de arreglo1:", desviacion_estandar)

Arreglo 1: [ 4 24 13 46 17]
Arreglo 2: [78 28 39 98 51]

Suma: [ 82  52  52 144  68]
Resta: [-74  -4 -26 -52 -34]
Multiplicación: [ 312  672  507 4508  867]
División: [0.05128205 0.85714286 0.33333333 0.46938776 0.33333333]

Promedio de arreglo1: 20.8
Mediana de arreglo1: 17.0
Desviación estándar de arreglo1: 14.161920773680384


---
## Ejercicio 3: Índices y selección

1. Crea un arreglo de números del 1 al 25 y redimensionalo en una matriz de 5x5.
2. Selecciona:
  - La primera fila.
  - La última columna.
  - La submatriz de 3x3 en el centro de la matriz.

In [ ]:
# Crea un arreglo del 1 al 25 y redimensionalo en una matriz de 5x5
array = np.arange(1, 26).reshape(5, 5)
print(f"El arreglo es: \n{array}")

print("\nPrimera fila:")
print(array[0])

print("\nÚltima columna:")
print(array[:, -1])

print("\nSubmatriz de 3x3 en el centro:")
print(array[1:4, 1:4])

El arreglo es: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Primera fila:
[1 2 3 4 5]

Última columna:
[ 5 10 15 20 25]

Submatriz de 3x3 en el centro:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


---
## Ejercicio 4: Uso de `argmax` y `argmin`
1. Genera un arreglo aleatorio de 10 elementos.
2. Encuentra el índice del valor máximo y el índice del valor mínimo.
3. Cambia el valor máximo a 0 utilizando su índice.

In [ ]:
array = np.random.randint(0, 100, 10) # Crea un areglo con 10 valores aleatorios enteros entre 0 y 99
print(f"El arreglo es: \n{array}")

max_index = np.argmax(array) # Obtiene el índice del valor máximo
min_index = np.argmin(array) # Obtiene el índice del valor mínimo

print(f"\nEl índice del valor máximo es: {max_index}")
print(f"El índice del valor mínimo es: {min_index}")

array[max_index] = 0

print(f"\nEl arreglo modificado es: \n{array}") # Cambia el valor máximo (solo una vez) a 0

El arreglo es: 
[45  3 91 54 81 12 67 64 74 12]

El índice del valor máximo es: 2
El índice del valor mínimo es: 1

El arreglo modificado es: 
[45  3  0 54 81 12 67 64 74 12]


---
## Ejercicio 5: Filtrado y máscaras
1. Genera un arreglo de 20 elementos con valores entre -10 y 10.
2. Crea una máscara para seleccionar solo los valores positivos y otro para los valores negativos.
3. Imprime ambos subconjuntos de valores.

In [ ]:
array = np.random.randint(-10, 11, 20) # Crea un areglo con 20 valores aleatorios enteros entre -10 y 10
print(f"El arreglo es: \n{array}")

# Filtros
array_mask_positive = (array >= 0)  # Valores positivos
array_mask_negative = (array < 0) # Valores negativos

# Mensajes de salida
print(f"\nValores positivos: \n{array[array_mask_positive]}")
print(f"\nValores negativos: \n{array[array_mask_negative]}")

El arreglo es: 
[  5 -10  -2   5   5   8   0  -4   6   9   4  -3   6   9   8   3  -1  10
   8   8]

Valores positivos: 
[ 5  5  5  8  0  6  9  4  6  9  8  3 10  8  8]

Valores negativos: 
[-10  -2  -4  -3  -1]


---
## Ejercicio 6: Funciones universales
1. Crea un arreglo de números del 1 al 10.
2. Calcula la raíz cuadrada, el seno y el logaritmo de cada elemento.
3. Redondea cada valor del arreglo resultante a 2 decimales.

In [ ]:
array = np.arange(1, 11)  # Crea un arreglo con valores de 1 a 10
print(f"El arreglo es: \n{array}")

# Calculos
raiz_cuadrada = np.round(np.sqrt(array),2)
seno = np.round(np.sin(array),2)
logaritmo = np.round(np.log(array),2)

# Mensajes de salida
print(f"\nRaíz cuadrada: \n{raiz_cuadrada}")
print(f"\nRaíz cuadrada: \n{seno}")
print(f"\nRaíz cuadrada: \n{logaritmo}")

El arreglo es: 
[ 1  2  3  4  5  6  7  8  9 10]

Raíz cuadrada: 
[1.   1.41 1.73 2.   2.24 2.45 2.65 2.83 3.   3.16]

Raíz cuadrada: 
[ 0.84  0.91  0.14 -0.76 -0.96 -0.28  0.66  0.99  0.41 -0.54]

Raíz cuadrada: 
[0.   0.69 1.1  1.39 1.61 1.79 1.95 2.08 2.2  2.3 ]


---
## Ejercicio 7: Operaciones con matrices
1. Crea dos matrices de 3x3 con valores aleatorios.
2. Realiza las siguientes operaciones entre ambas matrices:
 - Suma
 - Multiplicación elemento a elemento
 - Producto matricial (dot product)
3. Calcula la transpuesta y la inversa (si existe) de una de las matrices.

In [ ]:
# Matriz 3x3 con valores aleatorios enteros de 0 a 99
array1 = np.random.randint(0, 100, (3,3))
array2 = np.random.randint(0, 100, (3,3))

print(f"El arreglo 1 es: \n{array1}")
print(f"\nEl arreglo 2 es: \n{array2}")

# Operaciones
suma = np.sum(array1 + array2) # Suma elementos a elemento entre matrices, y despues hace la suma total
multiplicacion_elemento = array1 * array2   # Multiplicacion elemento a elemento
producto_matricial = np.dot(array1, array2) # Producto punto entre matrices

# Mensajes de salida
print(f"\nSuma: \n{suma}")
print(f"\nMultiplicación elemento a elemento: \n{multiplicacion_elemento}")
print(f"\nProducto matricial: \n{producto_matricial}")

# Transpuesta
transpuesta = np.transpose(array1)
print(f"\nTranspuesta: \n{transpuesta}")

# Inversa
inversa = np.round(np.linalg.inv(array1),2)
print(f"\nInversa: \n{inversa}")

El arreglo 1 es: 
[[17 15 97]
 [37 37 50]
 [35 52 70]]

El arreglo 2 es: 
[[63 43 12]
 [45 56 96]
 [91 12 83]]

Suma: 
911

Multiplicación elemento a elemento: 
[[1071  645 1164]
 [1665 2072 4800]
 [3185  624 5810]]

Producto matricial: 
[[10573  2735  9695]
 [ 8546  4263  8146]
 [10915  5257 11222]]

Transpuesta: 
[[17 37 35]
 [15 37 52]
 [97 50 70]]

Inversa: 
[[-0.    0.08 -0.06]
 [-0.02 -0.05  0.06]
 [ 0.01 -0.01  0.  ]]


---
## Ejercicio 8: Estadísticas
1. Genera un arreglo de 100 elementos con números aleatorios enteros entre
1 y 100.
2. Calcula la media, la mediana, el valor máximo, el valor mínimo y la
desviación estándar.
3. Encuentra el percentil 25, 50 y 75 de los datos.

In [ ]:
array = np.random.randint(1, 101, 100) # Crea un areglo con 100 valores aleatorios enteros entre 1 y 100
print(f"El arreglo es: \n{array}")

# Calculos
media = np.mean(array)  # Media
mediana = np.median(array)  # Mediana
maximo = np.max(array)  # Valor máximo
minimo = np.min(array)  # Valor minimo
desviacion_estandar = np.std(array) # Desviacion estandar

# Mensajes de salida
print(f"\nMedia: {media}")
print(f"Mediana: {mediana}")
print(f"Valor máximo: {maximo}")
print(f"Valor mínimo: {minimo}")

# Calculo de percentiles
percentil_25 = np.percentile(array, 25) # Percentil 25
percentil_50 = np.percentile(array, 50) # Percentil 50
percentil_75 = np.percentile(array, 75) # Percentil 75

# Mensajes de salida
print(f"\nPercentil 25: {percentil_25}")
print(f"Percentil 50: {percentil_50}")
print(f"Percentil 75: {percentil_75}")

El arreglo es: 
[ 39  61   7  29  40  83  32  45  68  53  22  45  96  66  24  50  62  95
  21  39  10  45  55  86  35  64  53  41  82  26  68  50  46  36  23  58
  86  22  67  26  57  53  88  40   7  76  16   1  30  15   8  23  71  36
  33  98  73  30  31  81  27  34   7  11  38  86 100  47  33  13  61  59
   8  56  19  76  58  96  79  30  75  63  10  72  28  38  53  47  22  30
  81  20  40  80  50  96  26  24  43  37]

Media: 46.96
Mediana: 44.0
Valor máximo: 100
Valor mínimo: 1

Percentil 25: 26.75
Percentil 50: 44.0
Percentil 75: 66.25


---
## Ejercicio 9: Concatenación y apilamiento
1. Crea dos arreglos de 1x5 y 5x1.
2. Concáténalos en una sola fila y una sola columna.
3. Apila ambos arreglos como una matriz 5x2.

In [ ]:
array1 = np.random.randint(0, 100, (1,5)) # Crea un areglo con valores aleatorios enteros entre 1 y 100
array2 = np.random.randint(0, 100, (5,1))

print(f"El arreglo 1 es: \n{array1}")
print(f"\nEl arreglo 2 es: \n{array2}")


# Concatenación
fila_concatenada = np.hstack((array1, array2.T))  # Transponer array2 para hacerlo una fila
columna_concatenada = np.vstack((array1.T, array2))  # Transponer array1 para hacerlo una columna

# Mensajes de salida
print(f"\nConcatenación fila: \n{fila_concatenada}")
print(f"\nConcatenación columna: \n{columna_concatenada}")

# Apilamiento
apilamiento = np.concatenate((array1.T, array2), axis=1)

# Mensajes de salida
print(f"\nApilamiento: \n{apilamiento}")

El arreglo 1 es: 
[[ 2 43 37 27 23]]

El arreglo 2 es: 
[[77]
 [43]
 [85]
 [44]
 [41]]

Concatenación fila: 
[[ 2 43 37 27 23 77 43 85 44 41]]

Concatenación columna: 
[[ 2]
 [43]
 [37]
 [27]
 [23]
 [77]
 [43]
 [85]
 [44]
 [41]]

Apilamiento: 
[[ 2 77]
 [43 43]
 [37 85]
 [27 44]
 [23 41]]


---
## Ejercicio 10: Manipulación de datos en matrices
grandes
1. Crea una matriz aleatoria de 100x100 con valores entre 0 y 1.
2. Calcula la suma de todos los elementos de la matriz.
3. Encuentra el valor máximo de cada fila y almacénalo en un nuevo arreglo.

In [ ]:
array = np.random.rand(100, 100) # Crea un areglo con valores aleatorios entre 0 y 1
print(f"El arreglo es: \n{array}")

suma = np.round(np.sum(array),2) # Suma de todos los elementos de la matriz
maximos = np.max(array, axis=1) # Valor máximo de cada fila

# Mensajes de salida
print(f"\nSuma de todos los elementos: {suma}")
print(f"\nValor máximo de cada fila: {maximos}")

El arreglo es: 
[[0.08608585 0.94711256 0.71254935 ... 0.412613   0.79420229 0.88380621]
 [0.36399149 0.86126376 0.42960666 ... 0.75557558 0.63927388 0.87437419]
 [0.54981694 0.59865318 0.64275546 ... 0.36615106 0.98796739 0.82892288]
 ...
 [0.15911094 0.60744199 0.23739287 ... 0.45027485 0.8328251  0.7106491 ]
 [0.05031533 0.77763275 0.2123676  ... 0.15326848 0.57669415 0.40366239]
 [0.81129458 0.83074749 0.42104115 ... 0.3142086  0.61885445 0.37878289]]

Suma de todos los elementos: 4994.47

Valor máximo de cada fila: [0.99602512 0.99902251 0.98861297 0.99538952 0.99458981 0.9987686
 0.99339958 0.99066831 0.98951661 0.99926143 0.99445785 0.98902274
 0.98677966 0.97596691 0.99103273 0.97522705 0.99690157 0.9944688
 0.99459362 0.96971238 0.99567618 0.99292033 0.97645908 0.99900373
 0.98011324 0.99550573 0.99901463 0.99972487 0.98880445 0.98208185
 0.97771589 0.99941636 0.99224344 0.98934286 0.98185036 0.99011599
 0.99617798 0.98693494 0.9992211  0.98239969 0.9951839  0.99668893
 0.9978

---
## Ejercicio 11: Ordenamiento y selección
1. Genera un arreglo de 10 números aleatorios entre 0 y 50.
2. Ordena el arreglo en orden ascendente y descendente.
3. Selecciona los 3 valores más altos y los 3 valores más bajos del arreglo
ordenado.

In [ ]:
array = np.random.randint(0, 51, 10) # Crea un areglo con 10 valores aleatorios enteros entre 0 y 50
print(f"El arreglo es: \n{array}")

# Ordenamiento
array_ascendente = np.sort(array) # Ordenamiento ascendente
array_descendente = np.sort(array)[::-1] # Ordenamiento descendente

# Mensajes de salida
print(f"\nArreglo ordenado ascendentemente: {array_ascendente}")
print(f"\nArreglo ordenado descendentemente: {array_descendente}")

maximos = array_descendente[:3] # 3 valores más altos
minimos = array_ascendente[:3] # 3 valores más bajos

# Mensajes de salida
print(f"\n3 valores más altos: {maximos}")
print(f"\n3 valores más bajos: {minimos}")

El arreglo es: 
[43 23 13 11 50 29  6  0  4 24]

Arreglo ordenado ascendentemente: [ 0  4  6 11 13 23 24 29 43 50]

Arreglo ordenado descendentemente: [50 43 29 24 23 13 11  6  4  0]

3 valores más altos: [50 43 29]

3 valores más bajos: [0 4 6]
