In [45]:
import tensorflow as tf
import numpy as np
print(f"GPUs disponibles {tf.config.list_physical_devices('GPU')}")

GPUs disponibles [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [46]:
a = np.array([1,2,3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(f"Tensor a: {t_a}")
print(f"Tensor b: {t_b}")

Tensor a: [1 2 3]
Tensor b: [4 5 6]


In [47]:
print(f"Es a un tensor {tf.is_tensor(t_a)}")
print(f"Es b un tensor {tf.is_tensor(t_b)}")

Es a un tensor True
Es b un tensor True


In [48]:
t_ones = tf.ones((2,3))
print(f"Tensor de unos {t_ones}")

print(f"Tensor de unos como array de Numpy: {t_ones.numpy()}")

Tensor de unos [[1. 1. 1.]
 [1. 1. 1.]]
Tensor de unos como array de Numpy: [[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(f"Tensor constante: {const_tensor}")

Tensor constante: [1.2       5.        3.1415927]


In [50]:
tensor_lleno = tf.fill((2,3), 3)
print(f"Tensor lleno: {tensor_lleno}")

Tensor lleno: [[3 3 3]
 [3 3 3]]


In [51]:
one_hot_tensor = tf.one_hot([0,1,2,3], 4)
print(f"One hot tensor: {one_hot_tensor}")

One hot tensor: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [52]:
t_a_new = tf.cast(t_a, tf.int64)
print(f"Tensor a convertido a int64: {t_a_new}")

Tensor a convertido a int64: [1 2 3]


In [53]:
t = tf.random.uniform(shape=(3,5))
t_tr = tf.transpose(t)

print(f"Tensor original: {t}")
print(f"Tensor transpuesto: {t_tr}")

Tensor original: [[0.2364521  0.23877335 0.50363123 0.77354    0.61077476]
 [0.8721783  0.2728473  0.6183162  0.20251584 0.8700757 ]
 [0.4924059  0.49692988 0.03011882 0.6857647  0.63157225]]
Tensor transpuesto: [[0.2364521  0.8721783  0.4924059 ]
 [0.23877335 0.2728473  0.49692988]
 [0.50363123 0.6183162  0.03011882]
 [0.77354    0.20251584 0.6857647 ]
 [0.61077476 0.8700757  0.63157225]]


In [54]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5,6))
print(f"Tensor original: {t}")
print(f"Tensor reshaped: {t_reshape}")

Tensor original: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
Tensor reshaped: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [55]:
t = tf.zeros((1, 2, 1, 4, 1))
t_sqz = tf.squeeze(t, axis=(2,4))
print(f"Tensor original: {t}")
print(f"Tensor squeezed: {t_sqz}")

Tensor original: [[[[[0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]]]]]
Tensor squeezed: [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [56]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5,2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5,2), mean=0.0, stddev=1.0)

t3 = tf.multiply(t1, t2).numpy()

print(f"t3 = {t3}")

t3 = [[-0.26996347 -0.87363994]
 [-0.01652765 -0.17496566]
 [-0.296179   -0.13944869]
 [-0.727211    0.13463593]
 [-0.40087393  0.00445271]]


In [57]:
t4 = tf.math.reduce_mean(t1, axis=0)
print(f"Media de t1 {t4}")

Media de t1 [0.08957257 0.2074099 ]


In [58]:
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print(f"Producto punto de t1 y t2: {t5}")

Producto punto de t1 y t2: [[-1.1436034   1.1154622  -0.86957175 -0.32104328  0.8555104 ]
 [ 0.24801862 -0.19149332  0.2504958  -0.06440266 -0.33072042]
 [-0.47782418  0.40717945 -0.4356277   0.02238923  0.5270062 ]
 [ 0.5247931  -0.23352589  0.74080014 -0.5925751  -1.1940589 ]
 [-0.09918738  0.26019517  0.12526006 -0.4623127  -0.39642122]]


In [59]:
t = tf.random.uniform((6,))

print(f"Tensor original {t}")

t_splits = tf.split(t, 3)
print(f"Tensor dividido en 3 partes: {t_splits}")

Tensor original [0.8292774  0.634228   0.5147276  0.39108086 0.5809028  0.04848182]
Tensor dividido en 3 partes: [<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.8292774, 0.634228 ], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5147276 , 0.39108086], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5809028 , 0.04848182], dtype=float32)>]


In [60]:
A = tf.ones((3,))
B = tf.zeros((2,))

C = tf.concat([A, B], axis=0)

print(f"Tensor A: {A}")
print(f"Tensor B: {B}")
print(f"Tensor C: {C}")

Tensor A: [1. 1. 1.]
Tensor B: [0. 0.]
Tensor C: [1. 1. 1. 0. 0.]


In [61]:
B = tf.zeros((3,))

S = tf.stack([A, B], axis=1)

print(f"Tensor A: {A}")
print(f"Tensor B: {B}")
print(f"Tensor apilado: {S}")

Tensor A: [1. 1. 1.]
Tensor B: [0. 0. 0.]
Tensor apilado: [[1. 0.]
 [1. 0.]
 [1. 0.]]
