## Coding Exercise #0102

### 1. NumPy array operations:

#### 1.1. '+' and '*' operators for Python lists:

In [3]:
import numpy as np

In [ ]:
a = [1, 2, 3]

In [ ]:
a + a

[1, 2, 3, 1, 2, 3]

In [ ]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
b = np.array([1, 2, 3])

In [ ]:
b*3

array([3, 6, 9])

In [ ]:
b + b

array([2, 4, 6])

In [ ]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
a+b

array([5, 7, 9])

In [ ]:
a-b

array([-3, -3, -3])

In [ ]:
a*b

array([ 4, 10, 18])

In [ ]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 1.3. Universal functions:

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5])

In [ ]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [ ]:
np.exp(x)   #e^x, donde 𝑒 es la constante matemática conocida como el número de Euler.

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [ ]:
type(np.sqrt)  #pertenece al módulo numpy

numpy.ufunc

In [ ]:
type(np.exp)  #pertenece al módulo numpy

numpy.ufunc

#### 1.4. NumPy functions:

In [4]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [5]:
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [6]:
np.unique(a)  #devuelve los valores únicos (es decir, sin repetidos) de un array o lista a, ordenados de forma ascendente.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.median(a)

5.0

In [8]:
np.sum(a)

5485

In [9]:
np.round(np.var(a),2)    #Calcula la varianza de los elementos en el array a. La varianza mide la dispersión de los datos con respecto a su media.

8.19

In [ ]:
np.round(np.mean(a),2)  #2 decimales

5.48

In [ ]:
np.round(np.std(a),2)    #Calcula la desviación estándar de los elementos en el array. La desviación estándar es la raiz cuadrada de la varianza.

2.86

In [ ]:
np.max(a)

10

In [ ]:
np.min(a)

1

#### 1.5. Statistical methods of NumPy arrays:

In [10]:
x=np.arange(1,11)

In [11]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x.sum()

55

In [ ]:
x.mean()

5.5

In [ ]:
x.std()

2.8722813232690143

In [ ]:
x.var()

8.25

In [ ]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(y.mean(axis=0))   # Calculamos la media a lo largo del eje 0 (columnas)

[4. 5. 6.]


In [ ]:
print(y.mean(axis=1)) # Calculamos la media a lo largo del eje 1  (filas)

[2. 5. 8.]


In [15]:
z = np.random.randint(10,size=1000)   #genera un array de 1000 elementos con números enteros aleatorios en el rango de 0 a 9 (excluyendo el 10).

In [14]:
z

array([2, 1, 6, 5, 3, 1, 5, 8, 8, 5, 5, 4, 9, 3, 3, 4, 1, 9, 5, 9, 7, 8,
       2, 8, 1, 6, 0, 2, 4, 5, 8, 4, 5, 0, 3, 7, 2, 5, 0, 0, 2, 2, 2, 7,
       8, 1, 0, 9, 7, 5, 8, 0, 2, 5, 9, 4, 4, 1, 3, 5, 8, 4, 2, 8, 9, 3,
       6, 2, 9, 8, 0, 5, 0, 7, 1, 6, 1, 6, 8, 0, 8, 7, 0, 0, 8, 2, 5, 8,
       9, 8, 4, 3, 6, 1, 5, 0, 8, 4, 2, 2, 2, 7, 5, 4, 4, 0, 6, 4, 7, 8,
       4, 7, 1, 2, 9, 3, 1, 2, 6, 4, 2, 8, 8, 3, 3, 7, 9, 9, 9, 9, 3, 9,
       0, 8, 7, 8, 9, 6, 7, 2, 5, 4, 2, 7, 5, 3, 1, 5, 1, 4, 6, 2, 2, 4,
       4, 9, 4, 6, 5, 6, 6, 9, 5, 2, 4, 5, 3, 4, 7, 1, 1, 7, 8, 8, 0, 9,
       2, 5, 8, 7, 7, 9, 1, 9, 6, 5, 8, 8, 4, 0, 1, 4, 1, 3, 7, 3, 4, 8,
       9, 6, 5, 7, 4, 8, 8, 3, 4, 5, 6, 4, 0, 0, 9, 0, 0, 1, 4, 7, 0, 1,
       2, 9, 9, 7, 2, 8, 3, 4, 4, 4, 5, 5, 2, 4, 0, 9, 0, 3, 6, 7, 7, 7,
       9, 2, 1, 5, 3, 0, 0, 0, 7, 1, 3, 3, 6, 0, 8, 0, 8, 9, 0, 3, 7, 1,
       9, 5, 6, 0, 3, 6, 9, 9, 0, 5, 6, 8, 7, 1, 3, 1, 9, 1, 6, 9, 1, 2,
       6, 3, 6, 2, 1, 4, 6, 1, 3, 7, 3, 5, 7, 1, 7,

In [13]:
z.max()

9

In [ ]:
z.min()

0

In [ ]:
(z > 5).sum()

392

In [ ]:
np.unique(z) #devuelve los valores únicos (es decir, sin repetidos) de un array o lista a, ordenados de forma ascendente.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sorted(set(z))  #La función sorted() toma cualquier iterable (como un conjunto) y devuelve una lista ordenada de sus elementos.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]